"""
InfraGuard Enterprise Report Generation Service.

Generates professional PDF and CSV reports using live SQLite data.
Reuses existing database repository layer — no duplicate queries.
"""

import io
import csv
import logging
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

from ..database.db import (
    get_all_assets,
    get_dashboard_summary,
    get_discovery_history,
    get_monitoring_summary,
)

logger = logging.getLogger("infraguard.reports")

BRAND = "InfraGuard"
ORG_NAME = "InfraGuard Organization"
FOOTER_TEXT = "Generated by InfraGuard — Unified IT Infrastructure & Network Visibility Platform"

# ─── Colour palette ──────────────────────────────────────────────────────────
HEADER_BG = colors.HexColor("#0284C7")
HEADER_FG = colors.white
ROW_ALT    = colors.HexColor("#F0F9FF")
BORDER_CLR = colors.HexColor("#CBD5E1")


# ─── Shared PDF helpers ──────────────────────────────────────────────────────

def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle(
        "BrandTitle", parent=ss["Title"], fontSize=22, textColor=HEADER_BG,
        spaceAfter=4, fontName="Helvetica-Bold",
    ))
    ss.add(ParagraphStyle(
        "ReportSubtitle", parent=ss["Normal"], fontSize=11,
        textColor=colors.HexColor("#64748B"), spaceAfter=14,
    ))
    ss.add(ParagraphStyle(
        "SectionHeading", parent=ss["Heading2"], fontSize=13,
        textColor=HEADER_BG, spaceBefore=18, spaceAfter=6,
        fontName="Helvetica-Bold",
    ))
    ss.add(ParagraphStyle(
        "FooterStyle", parent=ss["Normal"], fontSize=7,
        textColor=colors.HexColor("#94A3B8"), alignment=1,
    ))
    return ss


def _header_block(styles, report_title, org_name=None):
    """Return story elements for the common report header."""
    now = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    org = org_name or ORG_NAME
    return [
        Paragraph(BRAND, styles["BrandTitle"]),
        Paragraph(f"<b>{report_title}</b>", styles["Heading1"]),
        Paragraph(f"Organization: {org}&nbsp;&nbsp;|&nbsp;&nbsp;Generated: {now}", styles["ReportSubtitle"]),
        HRFlowable(width="100%", thickness=1, color=BORDER_CLR, spaceAfter=12),
    ]


def _build_table(headers, rows, col_widths=None):
    """Build a styled ReportLab Table from header + row data."""
    data = [headers] + rows
    tbl = Table(data, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        ("BACKGROUND",    (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",     (0, 0), (-1, 0), HEADER_FG),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 8),
        ("FONTSIZE",      (0, 1), (-1, -1), 7.5),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING",    (0, 1), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
        ("GRID",          (0, 0), (-1, -1), 0.4, BORDER_CLR),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]
    # Alternate row shading
    for i in range(1, len(data)):
        if i % 2 == 0:
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), ROW_ALT))
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def _footer_block(styles):
    return [
        Spacer(1, 20),
        HRFlowable(width="100%", thickness=0.5, color=BORDER_CLR, spaceAfter=4),
        Paragraph(FOOTER_TEXT, styles["FooterStyle"]),
    ]


def _render_pdf(story, title="InfraGuard Report"):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=15 * mm, bottomMargin=15 * mm,
        title=title, author=BRAND,
    )
    doc.build(story)
    buf.seek(0)
    return buf


# ─── 1. Infrastructure Summary Report ────────────────────────────────────────

def generate_infrastructure_summary_pdf(org_name=None):
    logger.info("[Report] Generating Infrastructure Summary PDF")
    styles = _styles()
    dash = get_dashboard_summary()
    mon = get_monitoring_summary()

    story = _header_block(styles, "Infrastructure Summary Report", org_name)

    metrics = [
        ["Metric", "Value"],
        ["Total Assets", str(dash.get("total_assets", 0))],
        ["Healthy Devices", str(mon.get("healthy_count", 0))],
        ["Warning Devices", str(mon.get("warning_count", 0))],
        ["Offline Devices", str(mon.get("offline_count", 0))],
        ["Average Latency", f'{mon.get("avg_latency_ms", 0)} ms'],
        ["Average Packet Loss", f'{mon.get("avg_packet_loss_percent", 0)}%'],
        ["Infrastructure Health Score", dash.get("health_score", "N/A")],
        ["Risk Level", dash.get("risk_level", "N/A")],
        ["Latest Discovery", dash.get("last_discovery", "None") or "None"],
    ]
    story.append(Paragraph("Summary Metrics", styles["SectionHeading"]))
    tbl = Table(metrics, colWidths=[200, 280])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",     (0, 0), (-1, 0), HEADER_FG),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("FONTNAME",      (0, 1), (0, -1), "Helvetica-Bold"),
        ("GRID",          (0, 0), (-1, -1), 0.4, BORDER_CLR),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    for i in range(2, len(metrics)):
        if i % 2 == 0:
            tbl.setStyle(TableStyle([("BACKGROUND", (0, i), (-1, i), ROW_ALT)]))
    story.append(tbl)
    story += _footer_block(styles)
    return _render_pdf(story, "Infrastructure Summary Report")


# ─── 2. Asset Inventory Report ───────────────────────────────────────────────

def generate_asset_inventory_pdf(org_name=None):
    logger.info("[Report] Generating Asset Inventory PDF")
    styles = _styles()
    assets = get_all_assets()

    story = _header_block(styles, "Asset Inventory Report", org_name)
    story.append(Paragraph(f"Total Registered Assets: {len(assets)}", styles["SectionHeading"]))

    headers = ["ID", "IP Address", "Hostname", "Device Name", "Vendor", "Type", "Status", "Avail %", "First Seen", "Last Seen"]
    rows = []
    for a in assets:
        aid = f'#AS-{str(a["id"]).zfill(3)}'
        first = a.get("first_seen", "")[:16] if a.get("first_seen") else ""
        last = a.get("last_seen", "")[:16] if a.get("last_seen") else ""
        avail = f'{a.get("availability_percent", 100)}%'
        rows.append([
            aid, a.get("ip_address", ""), a.get("hostname", ""), a.get("device_name", ""),
            a.get("vendor", "Unknown"), a.get("device_type", "Unknown"),
            a.get("status", ""), avail, first, last,
        ])

    if rows:
        story.append(_build_table(headers, rows, col_widths=[38, 68, 62, 62, 48, 58, 42, 36, 62, 62]))
    else:
        story.append(Paragraph("No assets found in repository.", styles["Normal"]))

    story += _footer_block(styles)
    return _render_pdf(story, "Asset Inventory Report")


def generate_asset_inventory_csv():
    logger.info("[Report] Generating Asset Inventory CSV")
    assets = get_all_assets()
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Asset ID", "IP Address", "Hostname", "Device Name", "Vendor",
                      "Device Type", "Status", "Availability %", "Latency (ms)",
                      "Packet Loss (%)", "First Seen", "Last Seen"])
    for a in assets:
        writer.writerow([
            f'#AS-{str(a["id"]).zfill(3)}',
            a.get("ip_address", ""),
            a.get("hostname", ""),
            a.get("device_name", ""),
            a.get("vendor", "Unknown"),
            a.get("device_type", "Unknown"),
            a.get("status", ""),
            a.get("availability_percent", 100),
            a.get("latency_ms", 0),
            a.get("packet_loss", 0),
            a.get("first_seen", ""),
            a.get("last_seen", ""),
        ])
    buf.seek(0)
    return buf.getvalue().encode("utf-8")


# ─── 3. Discovery History Report ─────────────────────────────────────────────

def generate_discovery_history_pdf(org_name=None):
    logger.info("[Report] Generating Discovery History PDF")
    styles = _styles()
    history = get_discovery_history(limit=50)

    story = _header_block(styles, "Discovery History Report", org_name)
    story.append(Paragraph(f"Total Discovery Records: {len(history)}", styles["SectionHeading"]))

    headers = ["#", "Discovery Date", "Subnet", "Scanned", "Reachable", "Unreachable", "Duration"]
    rows = []
    for idx, h in enumerate(history, 1):
        scanned_at = h.get("scanned_at", "")[:19] if h.get("scanned_at") else ""
        rows.append([
            str(idx), scanned_at, h.get("subnet", ""),
            str(h.get("total_scanned", 0)), str(h.get("active_found", 0)),
            str(h.get("unreachable_count", 0)), f'{h.get("duration_seconds", 0)}s',
        ])

    if rows:
        story.append(_build_table(headers, rows, col_widths=[28, 110, 100, 58, 58, 64, 58]))
    else:
        story.append(Paragraph("No discovery history records found.", styles["Normal"]))

    story += _footer_block(styles)
    return _render_pdf(story, "Discovery History Report")


def generate_discovery_history_csv():
    logger.info("[Report] Generating Discovery History CSV")
    history = get_discovery_history(limit=50)
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["#", "Discovery Date", "Subnet", "Total Scanned",
                      "Reachable", "Unreachable", "Duration (s)"])
    for idx, h in enumerate(history, 1):
        writer.writerow([
            idx, h.get("scanned_at", ""), h.get("subnet", ""),
            h.get("total_scanned", 0), h.get("active_found", 0),
            h.get("unreachable_count", 0), h.get("duration_seconds", 0),
        ])
    buf.seek(0)
    return buf.getvalue().encode("utf-8")


# ─── 4. Monitoring Summary Report ────────────────────────────────────────────

def generate_monitoring_summary_pdf(org_name=None):
    logger.info("[Report] Generating Monitoring Summary PDF")
    styles = _styles()
    mon = get_monitoring_summary()
    dash = get_dashboard_summary()

    story = _header_block(styles, "Monitoring Summary Report", org_name)
    story.append(Paragraph("Monitoring Engine Health Overview", styles["SectionHeading"]))

    total = mon.get("healthy_count", 0) + mon.get("warning_count", 0) + mon.get("offline_count", 0)
    if total > 0:
        avail = round((mon.get("healthy_count", 0) + mon.get("warning_count", 0)) / total * 100, 1)
    else:
        avail = 0.0

    metrics = [
        ["Metric", "Value"],
        ["Monitoring Status", "Active (Background Daemon)"],
        ["Total Monitored Assets", str(total)],
        ["Healthy Devices", str(mon.get("healthy_count", 0))],
        ["Warning Devices", str(mon.get("warning_count", 0))],
        ["Offline Devices", str(mon.get("offline_count", 0))],
        ["Average Latency", f'{mon.get("avg_latency_ms", 0)} ms'],
        ["Average Packet Loss", f'{mon.get("avg_packet_loss_percent", 0)}%'],
        ["Infrastructure Availability", f'{avail}%'],
        ["Last Discovery Scan", dash.get("last_discovery", "None") or "None"],
    ]
    tbl = Table(metrics, colWidths=[200, 280])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",     (0, 0), (-1, 0), HEADER_FG),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("FONTNAME",      (0, 1), (0, -1), "Helvetica-Bold"),
        ("GRID",          (0, 0), (-1, -1), 0.4, BORDER_CLR),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    for i in range(2, len(metrics)):
        if i % 2 == 0:
            tbl.setStyle(TableStyle([("BACKGROUND", (0, i), (-1, i), ROW_ALT)]))
    story.append(tbl)

    story += _footer_block(styles)
    return _render_pdf(story, "Monitoring Summary Report")
